user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    # Basic settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Redirect HTTP to HTTPS
    # server {
    #     listen 8080;
    #     server_name car-docker.onrender.com;
    #     return 301 https://$host$request_uri;
    # }

    # Your server block
    server {
        # listen 8080 ssl;
        listen 80;
        # server_name localhost;
        server_name _;
        # server_name car-docker.onrender.com;

        # No explicit SSL certificate is needed; Render handles it automatically
        # ssl on;  # Just to signify SSL is being used

        # ssl_certificate /etc/ssl/certs/your_cert.pem;  # Path to your SSL certificate
        # ssl_certificate_key /etc/ssl/private/your_key.pem;  # Path to your SSL certificate key

        root /var/www/public;

        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            # proxy_pass http://127.0.0.1:9000;  # Adjust according to your setup
            # proxy_pass http://app:9000;  # Use the service/container name
            # proxy_pass http://127.0.0.1:8080;  # Adjust according to your setup
            # proxy_set_header Host $host;
            # proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_read_timeout 300;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
